name: Fetch RSS arXiv and Post to Discord

on:
  schedule:
    - cron: "30 */6 * * *"  # 毎時0分に実行
  workflow_dispatch:

jobs:
  check_arxiv:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN を明示的に指定

      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 依存関係のインストール
        run: pip install requests feedparser

      - name: arXiv監視スクリプトを実行
        env:
          DISCORD_RSS_ARXIV_WEBHOOK_URL: ${{ secrets.DISCORD_RSS_ARXIV_WEBHOOK_URL }}
        run: python rss_arxiv_to_discord.py

      - name: 結果を保存
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MathRobotics/rss-to-discord.git
          git add posted_arxiv_papers.json
          git commit -m "Update posted papers" || exit 0
          git push
