name: Fetch RSS Twitter and Post to Discord

on:
  schedule:
    - cron: "0 */3 * * *"  # 3時間ごとに実行 (UTC時間)
  workflow_dispatch:

jobs:
  fetch_and_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN を明示的に指定

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install feedparser requests

      - name: Run Script
        env:
          DISCORD_RSS_TWITTER_WEBHOOK_URL: ${{ secrets.DISCORD_RSS_TWITTER_WEBHOOK_URL }}
        run: python rss_twitter_to_discord.py

      - name: Commit and Push Updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MathRobotics/rss-to-discord.git
          git add posted_twitter_post.json.json
          git commit -m "Update posted_twitter_post.json.json" || exit 0
          git push origin main
